### ISSUE TITLE
Unclear difference between `Channel` and `Session`

### ISSUE THREAD

**Issue by Kittenlover229** [warp-tech/russh#125]
Currently the comments on both are very autological and it seems deeply unobvious to me which one of them is for what. That resulted in the following questions arising:

1. Which one can I use to uniquely identify a connected client? 
2. They both have IDs, are they unique? 
3. Why is `ChannelID` a vocabulary type and `Session`'s id is not?
4. Should all data from all connections of the same session be syphoned into a single Sender for app-level logic? 

Perhaps they are in the documentation or require external knowledge of the SSH protocol in general, so I would be grateful to know where I can learn more. Maybe also make note of all mentioned above in the documentation too.

**Comment by Eugeny** [comment]
1. You identify clients yourself based on unique Session objects
2. Sessions don't have IDs. Channel IDs are unique within a session.
3. You're probably referring to an example where an "id" field is manually added to the Handler impl on the library consumer side.
4. Session == connection and internally has a single sender for all events

In the SSH protocol, separate channels are used within the single connection to separate multiple shell, SFTP and socket forwarding streams

**Comment by Kittenlover229** [comment]
Regarding the second one, I assume `Session`'s id [here](https://github.com/warp-tech/russh/blob/94aea49781eadf91475ae79d795b0cb7e75632f6/russh/src/server/session.rs#L21) accessible through [this](https://github.com/warp-tech/russh/blob/94aea49781eadf91475ae79d795b0cb7e75632f6/russh/src/server/session.rs#L485) method is part of the session interface since it is publicly available.

**Comment by Eugeny** [comment]
Oh right, that's a remnant from the original `thrussh` source code. It's just a unique numeric ID that servers no other purpose. 
It's redundant now though since you can add arbitrary information to your `Handler` implementation.

**Comment by mwileczka** [comment]
@Kittenlover229 I agree, the terms used in russh are confusing. russh uses the term "session" to mean connection. If you go by the [SSH RFCs](https://www.rfc-editor.org/rfc/rfc4254) after a connection is made, you use channels (which have IDs and are multiplexed on the connection) to establish "sessions" for shells, commands, file transfers, etc. You can have multiple "sessions" going at once per "connection". They really should rename `create_session` to `create_connection` or something else because they already have `channel_open_session` for the proper RFC usage. Not trying to blame anyone, I know this came from thussh, it's just really confusing,
