### ISSUE TITLE
Explain the reasons of the fork better

### ISSUE THREAD

**Issue by P-E-Meunier** [warp-tech/russh#151]
As the original author of the project, I would have appreciated a little email to explain why you weren't able to contribute your changes back.

Also, if you don't explain what "extra safety guarantees" you added, please remove that line in the readme: either you found safety problems in my code and you should have reported them, or you didn't, and you can't claim my code needed extra safety.

**Comment by Eugeny** [comment]
I've submitted my changes as patches over a year ago and got no response: https://nest.pijul.com/pijul/thrussh/discussions/69

`extra safety guarantees` refers to removing all sources of panicking in the library such as `.expect()`, `.unwrap()` and unchecked indexing - it's explained [in the readme](https://github.com/warp-tech/russh#safety)

**Comment by Eugeny** [comment]
> I don't think you would accept PRs to this repo formatted as links to diffs against an unnamed commit. Also, you started this fork before submitting these.

This is beyond the point. You've made it unreasonably hard to contribute by rolling your own VCS and failed to communicate back when offered a changeset in alternative way. If you look at the URLs in the post, you can see that I haven't even renamed the repo at the time and have only been using it as code storage.

> Did you identify places where an .unwrap() or .expect() can cause a safety problem? I believe all unwraps are legit in Thrussh, since the panicking branch is unreachable. I would suggest reformulating your "extra safety guarantees" as "using more lints (from Clippy)".

I mean things like [line 341](https://nest.pijul.com/pijul/thrussh:main/7FRJYUI62VW24.QXNQK) where a misbehaving server causes the library to panic, or `.unwrap()` on file I/O like on [line 325](https://nest.pijul.com/pijul/thrussh:main/7FRJYUI62VW24.KZKAA) Anyway, changed the wording :v:

**Comment by P-E-Meunier** [comment]
> with user support like this, I wonder why more people aren't using it

Maybe because this was never directly reported as an issue in the Pijul or Thrussh repos, nor even mentioned or discussed in the community platforms (Zulip, Discourse)?

**Comment by Eugeny** [comment]
@P-E-Meunier guess it just doesn't get better than straight up lying in an invite-only community where you know you won't get called out: https://lobste.rs/s/bikpmo/russh_rust_ssh_client_server_library

> The original motivation for the fork was aggressive (they didn’t talk to us initially) and was motivated by a misunderstanding of whether a feature was present or not.

> hostile forks by people just adding micro-features and claim ownership

> forking it to [...], claim ownership of my work 

> “More secure” and “up to date” was in their README at some poin

**Comment by P-E-Meunier** [comment]
So, now in addition to being a terrible person for being upset that you never upstreamed your changes, I'm also a liar and conspiring against you.

Did I lie by saying it was in the readme rather than in this issue? I'm so sorry.

Also, why not completely quote me? For example when I wrote the following:

> (note that I’m not even complaining about the fork, just about how its hostile nature: never contributing anything back)

**Comment by Eugeny** [comment]
> So, now in addition to being a terrible person for being upset that you never upstreamed your changes, I'm also a liar and conspiring against you.

Yes, unless you want to explain why you're spreading literal false information.

> Did I lie by saying it was in the readme rather than in this issue? I'm so sorry.

It's literally in neither, at any point of time.

> Also, why not quote me completely?
>> (note that I’m not even complaining about the fork, just about how its hostile nature: never contributing anything back)

Because I didn't want to embarrass you more than necessary, as that's literally [in my first response](https://github.com/warp-tech/russh/issues/151#issuecomment-1475453031)

You've simply [ignored](https://nest.pijul.com/pijul/thrussh/discussions/69) the contributions offered, so I just assumed that the project that [hasn't had a commit](https://nest.pijul.com/pijul/thrussh/changes) in 6 months [at that point in time](https://nest.pijul.com/pijul/thrussh/discussions/69) is unmaintained, forked it, and kept silently working on [my project](https://github.com/warp-tech/warpgate) that I needed the library for - until you have opened this issue to cry about getting forked, and only then resumed work on thrussh, 1.5 years since the last update.

You're welcome to pull in all of my changes, in fact, if you do, I'll replace this crate with a placeholder pointing to thrussh.
